#!/usr/bin/env python3
"""The CURRENT BUILD STATUS block in `agent-improve/docs/CONTINUITY.md`. Step 6.67.

ONE generator, TWO consumers: `.githooks/pre-commit` (via
`pre-commit-continuity.py`) regenerates the block and stages CONTINUITY.md; the
commit-msg guard's rule 5 verifies the staged block is what regeneration gives.

Since 6.67 every figure comes from `tools/control_board/features.py` — the
feature list and the recorded test run — and the headline is the board's,
character for character (`check_board.py` refuses a difference). The
procedure is archived; `PROCEDURE` now names the ARCHIVED copy, read only as
the frozen register behind the guard's rule 8 (old step and gap numbers).
The pre-6.67 generator: `docs/_archive/retired-tooling/hooks/continuity_status.py`.

Stdlib only: the guard imports this under the system python.
"""
from __future__ import annotations

import datetime as _dt
import os
import re
import subprocess
import sys

#: The archived procedure — the frozen step and gap register (rule 8).
PROCEDURE = "agent-improve/docs/_archive/REFACTORING_PROCEDURE.md"
CONTINUITY = "agent-improve/docs/CONTINUITY.md"
CLAUDE_MD = "agent-improve/CLAUDE.md"
ARCH_MD = "agent-improve/ARCHITECTURE.md"
BEGIN = "<!-- BEGIN CURRENT BUILD STATUS -->"
END = "<!-- END CURRENT BUILD STATUS -->"

_CLAUDE_V = re.compile(r"^#\s*Version\s+(?P<v>\S+)", re.M)
_ARCH_V = re.compile(r"^Version\s+(?P<v>\d+(?:\.\d+)+)", re.M)


def _run(args: list[str], cwd: str) -> str:
    out = subprocess.run(args, capture_output=True, encoding="utf-8", errors="replace",
                         cwd=cwd, timeout=15)
    return out.stdout if out.returncode == 0 else ""


def staged_text(path: str, cwd: str) -> str:
    """The staged blob for `path`, or the working-tree file when unstaged."""
    text = _run(["git", "show", f":{path}"], cwd)
    if text:
        return text
    try:
        with open(os.path.join(cwd, path), encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""


def _features(cwd: str):
    sys.path.insert(0, os.path.join(cwd, "agent-improve", "tools", "control_board"))
    import features
    return features


def build_block(cwd: str, today: str | None = None) -> str:
    f = _features(cwd)
    feats = f.load()
    s = f.summary(feats)
    by_id = {x["id"]: x for x in feats}
    claude = _CLAUDE_V.search(staged_text(CLAUDE_MD, cwd))
    arch = _ARCH_V.search(staged_text(ARCH_MD, cwd))
    date = today or _dt.date.today().isoformat()
    lanes = [f"| **Next — lane {k}** | {v['next']} — {by_id[v['next']]['description'][:140]} |"
             if v["next"] else f"| **Next — lane {k}** | every feature passes |"
             for k, v in s["lanes"].items()]
    return "\n".join([
        BEGIN,
        "<!-- Generated by .githooks/pre-commit; verified by the commit-msg",
        "     guard's rules 5 and 10. Do not hand-edit — it is rewritten from",
        "     tools/control_board/features.py on the next commit. -->",
        "",
        "## CURRENT BUILD STATUS",
        "",
        "| | |",
        "|---|---|",
        f"| **Headline** | {f.headline(s)} |",
        *lanes,
        f"| **Run-through record** | {'current' if f.runthrough_fresh() else 'older than the product source — re-run scripts/define_runthrough.py'} |",
        f"| **ARCHITECTURE.md** | v{arch.group('v') if arch else '—'} |",
        f"| **CLAUDE.md** | v{claude.group('v') if claude else '—'} |",
        f"| **Block regenerated** | {date} |",
        "",
        "*Every figure comes from `docs/define_features.json` and",
        "`docs/test-results.json` (step 6.67); the headline is the board's.",
        "A feature passes only when its end-to-end test passes.*",
        END,
    ])


def extract_block(text: str, begin: str = BEGIN, end_marker: str = END) -> str | None:
    """The existing block, or None when the file carries no markers."""
    start, end = text.find(begin), text.find(end_marker)
    if start == -1 or end == -1 or end < start:
        return None
    return text[start: end + len(end_marker)]


def splice(text: str, block: str, begin: str = BEGIN, end_marker: str = END) -> str:
    """Replace the block, or insert it at the very top of the file."""
    existing = extract_block(text, begin, end_marker)
    if existing is not None:
        return text.replace(existing, block, 1)
    return block + "\n\n" + text


__all__ = ["PROCEDURE", "CONTINUITY", "CLAUDE_MD", "ARCH_MD", "BEGIN", "END",
           "staged_text", "build_block", "extract_block", "splice"]
