"""The register has ONE source. Step 6.38.

WHY THIS FILE EXISTS, AND WHY IT IS NOT CALLED `test_register_dual_read`
------------------------------------------------------------------------
It was, until this step. The dual-read let every reader of the gap register and
the BUILT markers resolve from either `REFACTORING_PROCEDURE.md` or
`ARCHITECTURE.md`, and it existed for exactly one reason: **the commit that
moved the register could not otherwise be committed at all.** Rule 8 resolves a
`Gap: G-nn` trailer against the register read from the index, and 6.37 staged an
`ARCHITECTURE.md` with the register removed — so the guard would have refused
the edit that taught it where to look.

With the move complete the dual-read was **two sources of truth**, which is the
condition the repartition was performed to end. `_register_source.py` is
deleted, and a test asserting that there is no dual read must not be filed under
a name that says there is one — `test_middleware_execution_order` was renamed
for that reason on 2026-09-13, and the argument is the same.

WHAT WAS CHECKED BEFORE ANYTHING WAS DELETED
--------------------------------------------
The fallback was proven DEAD rather than assumed to be:

    ARCHITECTURE.md alone   ->  0 markers,  0 gaps
    the procedure alone     -> 81 markers, 74 gaps
    the dual-read, live     -> 81 markers, 74 gaps

and the board regenerated byte-identically across the removal at a fixed
commit, `26591e58c5cbecf943469aa7dbb1fddf`.
"""
from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

_ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                       capture_output=True, text=True).stdout.strip()
_HOOKS = Path(_ROOT) / ".claude" / "hooks"
_ARCH = Path(_ROOT) / "agent-improve" / "ARCHITECTURE.md"


def _hook(name: str, mod: str):
    if str(_HOOKS) not in sys.path:
        sys.path.insert(0, str(_HOOKS))
    spec = importlib.util.spec_from_file_location(mod, _HOOKS / name)
    assert spec and spec.loader, f"{name} is not where this file thinks it is"
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


@pytest.fixture(scope="module")
def board():
    return _hook("build_board.py", "build_board")


@pytest.fixture(scope="module")
def guard():
    return _hook("commit-msg-refactor-guard.py", "commit_msg_refactor_guard")


def test_the_scaffolding_is_gone() -> None:
    """**A permanent dual-read is two sources of truth.**

    6.36 wrote the removal step number into the code rather than into a note,
    on rule 8's own argument: a deadline that resolves nowhere schedules
    nothing. This is that deadline arriving.
    """
    assert not (_HOOKS / "_register_source.py").exists()
    for hook in sorted(_HOOKS.glob("*.py")):
        src = hook.read_text(encoding="utf-8")
        assert "_register_source" not in src, f"{hook.name} still imports it"
        assert "REMOVED_BY_STEP" not in src, f"{hook.name} still names it"


def test_no_reader_names_architecture_md_as_a_register_source(board, guard) -> None:
    """`ARCHITECTURE.md` holds the architecture and nothing else since 6.37."""
    assert "ARCHITECTURE" not in Path(board.PROCEDURE).name
    assert board.PROCEDURE.endswith("REFACTORING_PROCEDURE.md")
    assert guard.cs.PROCEDURE.endswith("REFACTORING_PROCEDURE.md")


def test_the_fallback_really_was_dead_before_it_was_deleted(board) -> None:
    """**The measurement that made the deletion safe, kept as an assertion.**

    If `ARCHITECTURE.md` ever regrows a marker or a gap row it is drift — the
    bible carries no status — and this is what says so rather than the removal
    silently starting to lose data.
    """
    arch = _ARCH.read_text(encoding="utf-8")
    assert board._markers_in(arch) == []
    assert board._gaps_in(arch) == {}


def test_the_readers_still_return_what_the_dual_read_returned(board) -> None:
    """The counts, pinned, with every movement in this file's history recorded.

        69 -> 70  6.37: the prose-form marker at §39.1.11 was normalised
        30 -> 31  that fact is `☐ not built`
        75 -> 74  6.37: G-19 struck through at last — it read `✅ CLOSED by
                  ruling` while the row was never struck, so every closure
                  parse counted it OPEN and the board drew it live
        74 -> 75  6.40's registration of G-87
        70 -> 81  6.40: 11 rows, of which four are §39.2–§39.5 — 40 sections
                  depended on those four alone
        31 -> 42  all 11 are non-built
        75 -> 74  6.41: G-87 closed
        81 -> 82  the ruling on 6.40's eleven: §69.1 given a row — its
                  conventions were factored OUT of the twenty tool entries,
                  so no child restates them and the parent owns them
        74 -> 77  6.33: G-88, G-89 and G-90 registered by founder ruling —
                  the asks mirror reading a key `SupervisorState` does not
                  declare, `field_log.reason` declared and populated by
                  nothing, and the verification tooling parsing an error body
                  as data. **REGISTER-ONLY: none of the three is fixed in
                  that commit.** The MARKER counts above are untouched —
                  these are gap rows, and no marker changed state
        77 -> 78  6.52: G-92 registered — G-84's guarantee reopened, the
                  soft budget never ending a turn before the engine wall
        78 -> 77  6.52 B2: G-92 closed in the same step. A struck-through
                  (closed) row is not read as a gap row — which is also why
                  closing G-91 never moved this count
        77 -> 78  8.0 (executor slice): G-93 registered — open questions do
                  not fit the budget (row 2), owner 8.0
        78 -> 77  6.54: G-93 closed — the clients are built at startup, once
        77 -> 78  G-95 registered and closed in one commit (not counted),
                  G-96 registered open — layer 2a rejects the Confirm step
        78 -> 81  6.46: G-94 (empty case index searched), G-97 (duplicate
                  evidence upload), G-98 (interpretation unavailable)
        81 -> 80  G-96 closed — layer 2a judges against the script step
    """
    markers, gaps = board.read_markers(), board.read_gaps()
    assert len(markers) == 82, f"{len(markers)} markers, not 82"
    assert sum(1 for m in markers if m["state"] != "built") == 42
    assert len(gaps) == 80, f"{len(gaps)} gap rows, not 80"


def test_the_guard_resolves_a_gap_from_the_one_register(guard) -> None:
    got = guard._known_gaps(_ROOT)
    assert len(got) > 50, f"the register resolved to {len(got)} gaps"
    assert {"G-52", "G-57", "G-82", "G-86", "G-87"} <= got, (
        "G-52 and G-87 are struck through and must still parse — a closed gap "
        "is still a number that resolves")


def test_a_reader_given_a_document_with_no_register_yields_nothing(board) -> None:
    """Still fails SOFT, not loud. `build_board.main` must keep regenerating."""
    assert board.read_gaps("no register in this string") == {}
    assert board.read_markers("no markers here either") == []
