"""The architecture decision records — their status, their index, and what may change in one.
Brief Part F1 and F4 (founder, 2026-09-27).

    python tools/control_board/adrs.py            # the index, printed
    python tools/control_board/adrs.py --write    # rewrite the index block in docs/adr/README.md

A record's lifecycle is PROPOSED → ACCEPTED → SUPERSEDED. It is never edited, only
superseded: once ACCEPTED, the one change allowed is its status line becoming
`SUPERSEDED by NNNN`; a change to link targets only is allowed on any record (ruling 5).

The design gate (guard rule 19) binds the records placed through the new-requirement
procedure — number 0057 and later (founder, 2026-09-27). 0001–0056 are the architecture
sort's draft, PROPOSED until the founder rules on them.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
PROJECT = _HERE.parents[1]
ADR_DIR = PROJECT / "docs" / "adr"
README = ADR_DIR / "README.md"
#: The first record the design gate binds (founder, 2026-09-27).
GATED_FROM = 57
BEGIN, END = "<!-- BEGIN ADR INDEX (generated by tools/control_board/adrs.py) -->", "<!-- END ADR INDEX -->"

_FILE = re.compile(r"^(\d{4})-[\w-]+\.md$")
_STATUS = re.compile(r"^\**Status:?\**:?\s*(PROPOSED|ACCEPTED|SUPERSEDED)(?:\s+by\s+(\d{4}))?", re.M)
_TITLE = re.compile(r"^#\s+(?:ADR-)?\d+\.?\s*(?:—\s*)?(.*)$", re.M)
_LINK = re.compile(r"\[[^\]]*\]\([^)]*\)")


def parse(text: str) -> dict:
    """{title, status, superseded_by} of one record's text."""
    t = _TITLE.search(text)
    s = _STATUS.search(text)
    return {"title": t.group(1).strip() if t else "", "status": s.group(1) if s else "PROPOSED",
            "superseded_by": s.group(2) if s and s.group(2) else None}


def load(folder: Path = ADR_DIR) -> dict[str, dict]:
    """Every record by its four-digit number."""
    out = {}
    for f in sorted(folder.glob("*.md")):
        m = _FILE.match(f.name)
        if m:
            out[m.group(1)] = {"file": f.name, **parse(f.read_text(encoding="utf-8"))}
    return out


def gated(number: str) -> bool:
    """Does the design gate bind this record? (0057 and later.)"""
    return int(number) >= GATED_FROM


def index(records: dict[str, dict]) -> str:
    rows = [f"| [{n}]({r['file']}) | {r['title']} | {r['status']}"
            + (f" by {r['superseded_by']}" if r["superseded_by"] else "") + " |"
            for n, r in records.items()]
    return "\n".join([BEGIN, "| # | Decision | Status |", "|---|---|---|", *rows, END])


def with_index(readme: str, records: dict[str, dict]) -> str:
    a, b = readme.index(BEGIN), readme.index(END) + len(END)
    return readme[:a] + index(records) + readme[b:]


def _status_line(line: str) -> bool:
    return bool(_STATUS.match(line))


def change_refusal(old: str, new: str) -> str | None:
    """Why this change to a record may not land (guard rule 21), or None.

    Any record: a change to link targets only is allowed (ruling 5). An ACCEPTED record:
    nothing else, except its status line becoming `SUPERSEDED by NNNN`."""
    a, b = old.replace("\r\n", "\n").split("\n"), new.replace("\r\n", "\n").split("\n")
    if [_LINK.sub("[]()", x) for x in a] == [_LINK.sub("[]()", x) for x in b]:
        return None
    if parse(old)["status"] != "ACCEPTED":
        return None
    if len(a) == len(b):
        diff = [(x, y) for x, y in zip(a, b) if x != y]
        if len(diff) == 1 and _status_line(diff[0][0]) and _status_line(diff[0][1]):
            p = parse(diff[0][1])
            if p["status"] == "SUPERSEDED" and p["superseded_by"]:
                return None
    return ("it is ACCEPTED, and an ACCEPTED record is never edited: the one change allowed "
            "is its status line to `Status: SUPERSEDED by NNNN` (a new record carries the new "
            "decision), or a change to link targets only")


def main(argv: list[str]) -> int:
    records = load()
    if "--write" in argv:
        README.write_text(with_index(README.read_text(encoding="utf-8"), records), encoding="utf-8")
        print(f"adr index -> {README} ({len(records)} records)")
        return 0
    print(index(records))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
