# -*- coding: utf-8 -*-
"""
One page. Columns are the zones the step register itself assigns (UI, SUP, PHASE,
COACH, GATE, STORE, OPS), ordered as a turn travels them. Inside each column the
architecture's own marker groups appear with the step that owns each marker.

PROVENANCE, per block:
  DERIVED  — parsed from the repo board, which build_board.py generates from
             REFACTORING_PROCEDURE.md Appendix D and ARCHITECTURE.md's markers.
  RELAYED  — Claude Code's tree audits (208e4a7, 20-21 Sep) and commit reports
             (62d7f17, 23 Sep). Evidence from the code, not read by me.
  VERIFIED — read by me, against the named source, on the date given.
Nothing on this page is written from memory.
"""
SOURCE = ("repo board · generated by .claude/hooks/build_board.py from Appendix D and "
          "ARCHITECTURE.md markers · 47 of 90 · 22 Sep 2026 — since then 5dc10ff and 01e8f8a landed, RELAYED")

# ---------------------------------------------------------------- the columns
# markers: (state, section, owning step or "—" for 'no step owns this')  DERIVED
# have:    (state, component)                                           RELAYED
COLUMNS = [
 dict(key="UI", label="API surface and the browser", sub="container 1 · zone UI",
   when="the Belt opens the app, types a turn, and later approves a gate",
   groups=[("1 · API surface", [
      ("w","§49 — API surface","10.1 · 7.3"),
      ("t","§50.1 — Coach response structure","6.19")])],
   have=[("b","case list, create, open a case"),("b","one project = one thread, the case id"),
         ("b","POST /ask — one turn, one graph run"),("b","upload · summarise · health"),
         ("b","send a turn, get a coached reply"),("b","upload evidence"),
         ("b","GET /gate/review — 200 on a real case since 01e8f8a"),
         ("b","the gate review panel — correct v2 rows with tier pills"),
         ("p","progress counter — 26 old names against the new store"),
         ("p","errors — a raw exception in a 3-second toast"),
         ("a","the four coaching blocks on screen"),("a","/ask/stream"),
         ("b","POST /gate submit uses the preview's assembly — 90948de"),
         ("b","the gate write merges and is safe twice — 90948de"),
         ("a","an approve endpoint"),("a","a route that can answer a pause"),
         ("a","a gate document screen")]),

 dict(key="SUP", label="Supervisor graph", sub="container 2 · zone SUP",
   when="main state is initialised and the phase subgraph is invoked",
   groups=[("2 · Supervisor graph", [])], clean="no open markers in the architecture",
   have=[("b","SupervisorState — 7 fields, no captured data"),
         ("b","the phase node invokes the Define subgraph"),
         ("b","input mapper — dispatched through a lookup table"),
         ("a","output mapper — built, not called, by ruling"),
         ("p","phase advancement driven by the HTTP route, not the graph")]),

 dict(key="PHASE", label="Phase subgraphs", sub="container 3 · zone PHASE",
   when="the planner picks the field, and the phase holds its own state",
   groups=[("3 · Phase subgraphs", [
      ("w","§39.1 — Define, complete specification","6.20"),
      ("w","§39.1.2 — ordered field list / field_index (G-38)","6.20"),
      ("w","§39.2 — Measure, complete specification","—"),
      ("t","§39.2.2 — Measure's ordered field list","—"),
      ("w","§39.2.7 — Measure's use of PhaseState","6.20"),
      ("w","§39.3 — Analyse, complete specification","—"),
      ("t","§39.3.2 — Analyse's ordered field list","—"),
      ("w","§39.3.7 — Analyse's use of PhaseState","6.20"),
      ("w","§39.4 — Improve, complete specification","—"),
      ("t","§39.4.2 — Improve's ordered field list","—"),
      ("w","§39.4.7 — Improve's use of PhaseState","6.20"),
      ("w","§39.5 — Control, complete specification","—"),
      ("t","§39.5.2 — Control's ordered field list","—")])],
   have=[("b","PhaseState — 23 fields, shared by all five phases"),
         ("b","the five nodes wired and compiled"),
         ("b","13 gate-required Define fields declared"),
         ("b","the planner node, wired, three exits"),
         ("b","artifacts merge, not replace — 6.33"),
         ("b","field_log — dated, with prior value — 6.33"),
         ("p","the field/gate decision — a turn counter, says so in its own comment"),
         ("a","a predicate for “is this field complete”"),
         ("a","field_log.reason — declared, nothing populates it"),
         ("b","the Define metric entry — 01e8f8a")]),

 dict(key="COACH", label="Coaching agent, middleware and tools", sub="containers 4–6 · zone COACH",
   when="the model call itself — what goes in, what comes back, what it may reach for",
   groups=[("4 · Coaching agent", [
      ("t","§26 — Multi-hop retrieval","6.10"),
      ("w","§43.1 — the seven-step computation pattern","—"),
      ("w","§43.2 — show before asking","—"),
      ("t","§43.3 — the A→F session flow","—"),
      ("t","§43.4 — live gate document preview","—"),
      ("w","§43.5 — no external URLs","—"),
      ("w","§43.6 — what the coach must not do","—"),
      ("w","§43.7 — metric literacy: the metric, and the statistic","—")]),
    ("5 · Middleware", [
      ("w","§19.6 — ContradictionDetectionMiddleware, the mid-phase check","7.3 · 7.6")]),
    ("6 · Tools and knowledge", [
      ("w","§23 — the three indexes","9.1"),
      ("w","§29 — the data channel and the universal eight","7.1 · 7.5"),
      ("w","§30 — computation tools and per-phase binding","7.1 · 7.5")])],
   have=[("b","the executor — the only agent in the phase"),
         ("b","8 declared response fields"),
         ("b","the Define SKILL.md — 12 fields, explain · show · ask · confirm"),
         ("b","the metric literacy block in the skill"),
         ("b","mw1 state injection"),("p","mw2 skills — a catalogue, no record it was taken"),
         ("b","mw3 summarising"),("b","mw4 model retry"),("b","mw5 tool retry"),
         ("b","mw6 coaching grader — process, every turn"),
         ("b","mw7 coherence — every turn"),
         ("p","mw8 contradiction — ships inert, import kept"),
         ("b","7 tools bound — 3 retrieval, template, diagram, series, savings"),
         ("b","the evidence index — uploads, chunked, twelve fields"),
         ("b","the capture path checks each value against its declared type — 5dc10ff"),
         ("a","read an artefact"),("a","check_gate_status"),("a","request_human_approval"),
         ("a","the Define phase rubric — six criteria, no text")]),

 dict(key="STORE", label="Persistence", sub="container 8 · zone STORE",
   when="checkpoints during the turn, and the record written after the graph returns",
   groups=[("8 · Persistence and cross-cutting", [
      ("t","§44 — the failure pipeline","8.2"),
      ("t","§46 — the fallback chain and circuit breakers","8.3 · 8.4"),
      ("t","§48 — structured errors","8.1"),
      ("t","§51 — tracing and observability","8.0")])],
   have=[("b","the blob checkpointer — put, get_tuple, list, async wrappers"),
         ("b","the subgraph compiles with none and inherits the parent's"),
         ("b","the case record — fields, change log, citations, uploads"),
         ("p","writes during a node are a no-op"),
         ("p","no connection string = no persistence, and only a log line says so"),
         ("a","resume from a checkpoint — no rollback, no time travel"),
         ("a","a version on the write — last writer wins by default"),
         ("a","the knowledge index — schema exists, nothing ingested"),
         ("a","the case index — prior cases"),
         ("u","whether a checkpoint has ever been written")]),

 dict(key="GATE", label="Validation, gates, escalation", sub="container 7 · zone GATE",
   when="the phase closes: the checks run, the Belt approves, the record is written",
   groups=[("7 · Validation, gates, escalation", [
      ("t","§33 — the nine-step HITL gate","7.3"),
      ("w","§34 — the four-layer validation stack","7.2"),
      ("t","§35 — two tiers of field, and the warning verdict","7.4"),
      ("w","§36 — two graders, and why they are not redundant","7.1"),
      ("t","§37 — mid-phase contradiction and the re-approval cascade","7.6 · 7.3"),
      ("t","§38 — escalation","7.5"),
      ("t","§39.1.11 — conditions: routing and the gate","7.3"),
      ("t","§52 — evaluation and regression testing","7.0"),
      ("w","§63.6 — S-C32, the three cross-phase reference dicts","—"),
      ("w","§63.9 — S-C39, phase_metrics, the per-phase placeholder","—")])],
   have=[("b","2a coherence — middleware, every turn"),
         ("b","assemble() — assembles a real case, 18 keys"),
         ("p","2b field presence — built, runs only at the gate"),
         ("p","gate_review — logs and passes through, never pauses"),
         ("p","gate_apply — applies nothing, by design; the route does the write"),
         ("a","2c constraints"),("a","2d the phase rubric — the gate's own grader"),
         ("a","the five phase rubrics have coverage lists and no text"),
         ("a","the Store copy Measure reads — written by the mapper that does not fire")]),

 dict(key="OPS", label="Cross-cutting — reliability and governance", sub="zone OPS",
   when="not on the turn path: tracing, errors, the register, the guards, deleting v1",
   groups=[], clean="its markers are carried by container 8, above",
   have=[("b","the drift-check hook on every commit"),
         ("b","verify_built.py — 32 checks, zero disagreements at 62d7f17"),
         ("b","the step register and the gap register"),
         ("a","a check that compares the tree against the framework's own documentation")]),
]

# ------------------------------------------------- what the frameworks say
# VERIFIED by me at docs.langchain.com and learn.microsoft.com, 23 Sep 2026.
FRAMEWORK = [
 ("“the runtime restarts the entire node from the beginning — it does not resume from the "
  "exact line where interrupt() was called”",
  "so the gate-document write must be safe to perform twice",
  "6.42", "docs.langchain.com/oss/python/langgraph/interrupts"),
 ("“Do not perform non-idempotent operations before interrupt()… Do not create new records "
  "without checking if they exist.”",
  "a documented rule pointed straight at the gate write",
  "6.42", "docs.langchain.com/oss/python/langgraph/interrupts"),
 ("interrupt() is documented in node functions and in tools. Middleware is not mentioned.",
  "the stop belongs in a node — 7.3's clause 1 is superseded in placement, not in substance",
  "6.44", "docs.langchain.com/oss/python/langgraph/interrupts"),
 ("“To use interrupt(), you need: 1. A checkpointer to persist the graph state”",
  "and whether ours has ever written is not knowable from the tree — assert it at runtime",
  "7.3", "docs.langchain.com/oss/python/langgraph/interrupts"),
 ("“it is assumed that all updates to that key should override it” — with no reducer declared",
  "every accumulating channel needs a reducer, or a write site can silently replace",
  "S26", "docs.langchain.com/oss/python/langgraph/graph-api"),
 ("separate input_schema and output_schema are supported on StateGraph",
  "the boundary the output mapper is meant to own is a first-class framework feature",
  "S25", "docs.langchain.com/oss/python/langgraph/graph-api"),
 ("“if you don't explicitly specify a strategy, then by default the last writer wins”",
  "the case-record write carries no version, and a second writer arrives at stage 7",
  "S25", "learn.microsoft.com · Azure Blob concurrency"),
]

# ------------------------------------------------- real, and not carded
FINDINGS = [
 ("baseline_estimate is stored as a sentence fragment",
  "the live 200 at 01e8f8a carries baseline_estimate \u201c\u2026averaging 12.78.\u201d beside target_value \u201c3%\u201d. "
  "\u00a763.1 B7 requires both as DISCRETE values because Control parses them for target-versus-actual. "
  "The type is str, so the type check cannot catch it; only a value check can. Blocks nothing in flight.",
  "RELAYED \u00b7 01e8f8a \u00b7 findings list"),
 ("CO-1 — captured values do not carry their declared type",
  "four gate-required Define fields are declared structured and captured as prose, so no gate "
  "document can assemble on real data. ADMITTED: it blocks 6.20's live clause and 6.42 entirely. "
  "Needs a number.", "RELAYED · 62d7f17"),
 ("6.48 — the graph owns its boundary, with a version on the write",
  "the output mapper is not called and the HTTP route writes instead; the write carries no version "
  "while Azure defaults to last-writer-wins.", "proposed · not in the register"),
 ("6.49 — accumulating channels carry reducers",
  "merging is done by hand in application code where the framework offers a reducer that cannot "
  "be forgotten.", "proposed · not in the register"),
 ("§16's persistence claim contradicts the tree",
  "the G-44 rule says the wrapper's inner invoke persists PhaseState across Belt turns; the route "
  "comment, the turn-two test and 6.33's whole design all say it does not.",
  "RELAYED · 62d7f17 · first output of the conformance pass"),
 ("§43.1–§43.7 — seven coaching-behaviour markers owned by nothing",
  "the seven-step computation pattern, show before asking, the A→F session flow, the live gate "
  "preview, no external URLs, what the coach must not do, metric literacy. The largest unowned "
  "block in the architecture, and it sits inside the vertical being refactored.", "DERIVED"),
 ("§63.9 — phase_metrics reads owned by nothing while 6.20 builds it",
  "6.20 should claim the marker in its commit, or it will read open after the work has landed.",
  "DERIVED"),
 ("Project members and sign-in",
  "a case is opened against a free-text name. Out of scope now. The constraint on work in flight: "
  "field_log entries and the gate approval record each carry an ACTOR value from the outset, so "
  "identity can be substituted later without changing either structure.",
  "founder, 23 Sep · forward dependency"),
]

# NEXT is no longer declared here. It is DERIVED by stories.next_story(): the
# top-ranked story that is not done, whose status comes from Appendix H.


# ---------------------------------------------- the architecture, folded in
# Which arch_view blocks belong under which column. The content itself lives in
# arch_view.py (RELAYED from the tree audit at 208e4a7 + the ratified sections).
SPEC = {
 "SUP":   dict(level="LEVEL1"),
 "PHASE": dict(level="LEVEL2", nodes=["Phase planner"], phases=True),
 "COACH": dict(nodes=["Phase executor \u2014 the coach"], middleware=True, tools=True),
 "GATE":  dict(nodes=["Validation stack", "Gate review", "Gate apply"], validation=True),
 "STORE": dict(stores=True),
}


# --------------------------------------------------- the procedure's stages
# Membership and counts are DERIVED at build time from the step numbers.
# Only stage 8's name is quoted from the document ("Part 7 — Stage 8: Reliability",
# carried verbatim by the repo board). The others are described from the titles of
# the steps they contain and are marked as such.
STAGE_NOTE = ("A stage is the step-number prefix: 6.42 is in stage 6. Membership and the counts below "
              "are derived from the register. Only stage 8 carries a name the document states; the rest "
              "are described from the steps they contain.")
STAGES = {
 "2": ("Upgrade the foundation", "dependencies, async, the LLM factory", False),
 "3": ("State, storage and the boundary", "SupervisorState, PhaseState, the mappers, the schemas", False),
 "4": ("The graphs", "the Define subgraph, the supervisor, the remaining four", False),
 "5": ("Retrieval and tools", "the three lookups, twenty computation tools, per-phase binding", False),
 "6": ("The coaching loop", "planner, executor, middleware, the write paths, the governance guards", False),
 "7": ("Validation, gates and escalation", "the four layers, the HITL gate, the approve endpoint", False),
 "8": ("Reliability", "telemetry, structured errors, timeouts, circuit breakers", True),
 "9": ("Indexes", "the knowledge corpus, the case index, the deployment quota", False),
 "10": ("The browser", "rendering the turn, progress, the gate screen, errors, streaming", False),
 "11": ("Close-out", "delete v1, close the governance register", False),
}

# ----------------------------------------------- the Define critical path
FASTPATH_NOTE = ("Ten steps \u2014 three were added on evidence. Three are done. Each one is specified and each "
                 "waits only on the one before it. The three things that need founder content \u2014 the "
                 "rubric text, the validator's result shape and the gate screen design \u2014 are NOT on "
                 "this line; that is the point of it.")
FASTPATH = [
 (1, "6.48", "stage 6", "A captured value carries its declared type",
  "enforced at capture; four structured fields refused as prose, per field, at both ends",
  "DONE \u00b7 5dc10ff", "row 18 green"),
 (2, "S-C05", "stage 6", "The declared shape travels with the type contract",
  "the shape is written on the field description, so it reaches the model every turn with nothing to fetch",
  "DONE \u00b7 5dc10ff, same commit", "row 18 green on live data, load_skill never called"),
 (3, "6.20", "stage 6", "The Define metric entry, and a complete case assembles",
  "GET /gate/review answers 200 with an 18-key document on a real case \u2014 it had answered 500 since before the audit",
  "DONE \u00b7 01e8f8a", "row 19 green"),
 (4, "6.42", "stage 6", "Submit uses the assembly; the write merges and is safe twice",
  "today submit builds from a key nothing sets and overwrites the whole Define record, dropping the change log and uploads",
  "NEXT \u00b7 brief sent", "gives rows 20 and 21"),
 (5, "\u2014", "stage 6", "Write the checks for the ten rows believed working",
  "no code changes: a check per row, reading the live case, so rows that work today are proven rather than assumed",
  "brief to write", "takes the register from 4 to 14 of 24"),
 (6, "6.46", "stage 6", "The coaching script reaches the model every turn, or its absence is recorded",
  "load_skill was called zero times in four live turns: the method never reached the coach",
  "brief written", "gives row 3"),
 (7, "10.3", "stage 10", "Progress counts the real field names",
  "today it reads 0 of 26 forever", "READY", "gives row 14"),
 (8, "6.44", "stage 6", "The contradiction stop moves out of middleware into a node",
  "the docs name node functions and tools as the places a run may stop", "READY", "prepares 7.3"),
 (9, "7.3", "stage 7", "The gate pauses, and the pause is resumable",
  "narrowed in place; the validation-consuming steps became 7.8", "queued", "needs 6.44 and 6.42's idempotent write"),
 (10, "7.7", "stage 7", "A route that answers the pause and resumes the run",
  "an interrupt with no resume parks the case forever", "queued", "gives row 23"),
]
FASTPATH_END = ("After step 7: coached \u00b7 captured \u00b7 assembled \u00b7 shown \u00b7 approved \u00b7 recorded. "
                "Provable in the browser for everything except the approve itself, which is one API call "
                "until the gate screen is designed.")


# ------------------------------------------------- Appendix H, draft
# NOT ratified. Appendix H is honestly 0 of 0 until the founder checks these.
# state: b green today | p amber, a stand-in | a red, absent
CAP_NOTE = ("A row is GREEN only when its check exists and passes. Exactly one does today \u2014 row 18, proven live at 5dc10ff. Every other row is UNPROVEN: some of them almost certainly work, and until a check says so that is an opinion, not a status. "
            "One row per thing a Belt must be able to do in Define, each with the single executable "
            "check that proves it. Green or red, no third value. This is what replaces \u201c47 of 90 "
            "steps\u201d as the measure of the vertical.")
CAPS = [
 ("COACHING \u2014 the Belt is guided through the twelve fields", [
  (1,"u","A case can be created and opened","the case list returns it and it opens",""),
  (2,"u","A turn returns a coached reply","one POST, one graph run, a message back",""),
  (3,"u","The coach follows the Define script for this field","the turn records that the script was loaded","6.46"),
  (4,"u","The Belt is asked for the RIGHT next field","field two is asked only once field one is complete","6.45"),
  (5,"u","A captured field survives the next turn","turn two captures the team; the business case is still there","6.33"),
  (6,"u","Every change is kept, dated, with its prior value","180,000 then 245,000, both readable","6.33"),
  (7,"u","The Belt's REASON for a change is recorded","field_log.reason is non-empty after a correction","6.44"),
  (8,"u","The Belt can upload evidence","the file lands and is indexed",""),
  (9,"u","The coach can READ an uploaded document","a turn quotes a line from the upload","6.43"),
  (10,"u","Calculations are recorded","computation_results carries the five keys","6.20"),
  (11,"u","A metric entry mirrors the primary scalars","phase_metrics equals baseline_estimate and target_value","6.20"),
  (12,"u","Vague or contradictory answers are caught in the turn","layer 2a rejects and re-asks, silently, max two",""),
  (13,"u","The coach's own process is graded every turn","the coaching rubric scores the turn",""),
 ]),
 ("SEEING \u2014 the Belt can tell where they are", [
  (14,"u","Progress shows the real field count","the bar reads 5 of 12, not 0 of 26","10.3"),
  (15,"u","The coaching blocks render on screen","explanation, example, prompt and citations are visible","10.0"),
  (16,"u","A failed turn gives a readable error","a backend failure says what happened, and stays on screen","10.4"),
 ]),
 ("THE GATE \u2014 Define is closed and recorded", [
  (17,"u","Required fields are checked before the gate","layer 2b refuses a case missing a required field",""),
  (18,"b","Captured values carry their declared type","team, scope, the SIPOC map and the registry arrive structured, not as prose","6.48"),
  (19,"b","A complete case ASSEMBLES a gate document","thirteen fields in, a document out \u2014 not a 500","6.20"),
  (20,"u","The document is WRITTEN, and safe to write twice","submit persists what assemble built","6.42"),
  (21,"u","The gate write preserves the change log and the uploads","field_log and uploads still there after submit","6.42"),
  (22,"u","Constraints and the quality rubric grade the document","2c and 2d run at the gate and can fail it","7.2 \u00b7 7.8"),
  (23,"u","The Belt SEES the document and approves it","the run pauses, and an answer resumes it","7.3 \u00b7 7.7 \u00b7 10.2"),
  (24,"u","The next phase can read Define's record","Measure starts without PriorGateDocumentMissing","stage 7"),
 ]),
]
CAP_FLAG_OLD = ("Row 18 is the one to look at hardest: it is turned green by TWO steps \u2014 6.48 makes the "
            "captured values typed, 6.20 supplies the metric entry, and assembly needs both. That is "
            "exactly the grain question Claude Code raised. Either it stays one row with two owners, or "
            "it splits into \u201cvalues carry their declared type\u201d and \u201ca complete case assembles\u201d "
            "and the register is 24 rows. Your call.")


# Which container each row lives in — so a red row points at a column of the system.
CAP_WHERE = {
 1:"1 browser", 2:"1 browser", 3:"4 coach", 4:"3 phase subgraph", 5:"3 phase subgraph",
 6:"3 phase subgraph", 7:"4 coach", 8:"1 browser", 9:"6 tools", 10:"3 phase subgraph",
 11:"3 phase subgraph", 12:"5 middleware", 13:"5 middleware",
 14:"1 browser", 15:"1 browser", 16:"1 browser",
 17:"7 gate", 18:"4 coach", 19:"7 gate", 20:"1 routes", 21:"1 routes",
 22:"7 gate", 23:"7 gate", 24:"8 persistence", 25:"3 phase subgraph",
 26:"4 coach", 27:"4 coach", 28:"4 coach", 29:"6 tools", 30:"4 coach", 31:"4 coach", 32:"4 coach",
 33:"8 persistence", 34:"7 gate", 35:"8 persistence",
}
CAP_FLAG = ("RULED, 23 September: row 18 is split out so that every row has exactly one owning step. "
            "24 rows. Each row names the container it lives in, so a red row points at a column of the "
            "system above. Nothing here needs checking before work starts \u2014 a row that turns out "
            "wrong is corrected when its check is written, which is cheaper than auditing all of them now.")


# ------------------------------------------- the register, in the order it turns green
# Row numbers are IDs (Appendix H uses them). The ORDER is when each row goes green.
CAP_BANDS = [
 ("PROVEN \u2014 green, with a check that reads the live case", "b", [18, 19],
  "Turned green by 6.48 + S-C05 (5dc10ff) and 6.20 (01e8f8a)."),
 ("NEXT ON THE PATH \u2014 in the order the stories will prove them", "o",
  [(20, "6.42"), (21, "6.42"), (25, "S33"), (3, "6.46"), (14, "10.3"), (7, "6.44"), (23, "7.3 + 7.7")],
  "Rows 20 and 21 are built and skipping honestly until a gate is submitted on a second case."),
 ("BELIEVED WORKING \u2014 no check written yet", "u", [1, 2, 5, 6, 8, 10, 11, 12, 13, 17],
  "These almost certainly work today. One card writes all ten checks at once \u2014 story S9, rank 2."),
 ("THE METHOD \u2014 after 6.46 puts the script in front of the coach", "u", [26, 27, 28, 29, 30, 31, 32],
  "\u00a743's seven rules. Each is meant to be a rubric criterion checked every turn, and each needs a check that "
  "watches a live turn \u2014 a file probe cannot tell whether the method is sound."),
 ("QUALITY \u2014 after Define works end to end", "q", [4, 9, 15, 16, 22, 24],
  "The planner's real predicate, reading uploads, the coaching blocks, readable errors, rubric grading, "
  "and Measure reading Define's record. Real, and none stops a Belt closing Define."),
]
CAP_SUMMARY = ("32 rows. After the ranked path: 2 proven + 7 on the path + 10 believed-working = 19 of 32. "
               "Then the method's seven, then the six quality rows.")
