# -*- coding: utf-8 -*-
"""
One page. Columns are the zones the step register itself assigns (UI, SUP, PHASE,
COACH, GATE, STORE, OPS), ordered as a turn travels them. Inside each column the
architecture's own marker groups appear with the step that owns each marker.

PROVENANCE, per block:
  DERIVED  — parsed from the repo board, which build_board.py generates from
             REFACTORING_PROCEDURE.md Appendix D and ARCHITECTURE.md's markers.
  RELAYED  — Claude Code's tree audits (208e4a7, 20-21 Sep) and commit reports
             (62d7f17, 23 Sep). Evidence from the code, not read by me.
  VERIFIED — read by me, against the named source, on the date given.
Nothing on this page is written from memory.
"""
SOURCE = ("repo board · generated by .claude/hooks/build_board.py from Appendix D and "
          "ARCHITECTURE.md markers · 47 of 90 · 22 Sep 2026 — since then 5dc10ff and 01e8f8a landed, RELAYED")

# ---------------------------------------------------------------- the columns
# markers: (state, section, owning step or "—" for 'no step owns this')  DERIVED
# have:    (state, component)                                           RELAYED
COLUMNS = [
 dict(key="UI", label="API surface and the browser", sub="container 1 · zone UI",
   when="the Belt opens the app, types a turn, and later approves a gate",
   groups=[("1 · API surface", [
      ("w","§49 — API surface","10.1 · 7.3"),
      ("t","§50.1 — Coach response structure","6.19")])],
   have=[("b","case list, create, open a case"),("b","one project = one thread, the case id"),
         ("b","POST /ask — one turn, one graph run"),("b","upload · summarise · health"),
         ("b","send a turn, get a coached reply"),("b","upload evidence"),
         ("b","GET /gate/review — 200 on a real case since 01e8f8a"),
         ("b","the gate review panel — correct v2 rows with tier pills"),
         ("p","progress counter — 26 old names against the new store"),
         ("p","errors — a raw exception in a 3-second toast"),
         ("a","the four coaching blocks on screen"),("a","/ask/stream"),
         ("b","POST /gate submit uses the preview's assembly — 90948de"),
         ("b","the gate write merges and is safe twice — 90948de"),
         ("a","an approve endpoint"),("a","a route that can answer a pause"),
         ("a","a gate document screen")]),

 dict(key="SUP", label="Supervisor graph", sub="container 2 · zone SUP",
   when="main state is initialised and the phase subgraph is invoked",
   groups=[("2 · Supervisor graph", [])], clean="no open markers in the architecture",
   have=[("b","SupervisorState — 7 fields, no captured data"),
         ("b","the phase node invokes the Define subgraph"),
         ("b","input mapper — dispatched through a lookup table"),
         ("a","output mapper — built, not called, by ruling"),
         ("p","phase advancement driven by the HTTP route, not the graph")]),

 dict(key="PHASE", label="Phase subgraphs", sub="container 3 · zone PHASE",
   when="the planner picks the field, and the phase holds its own state",
   groups=[("3 · Phase subgraphs", [
      ("w","§39.1 — Define, complete specification","6.20"),
      ("w","§39.1.2 — ordered field list / field_index (G-38)","6.20"),
      ("w","§39.2 — Measure, complete specification","—"),
      ("t","§39.2.2 — Measure's ordered field list","—"),
      ("w","§39.2.7 — Measure's use of PhaseState","6.20"),
      ("w","§39.3 — Analyse, complete specification","—"),
      ("t","§39.3.2 — Analyse's ordered field list","—"),
      ("w","§39.3.7 — Analyse's use of PhaseState","6.20"),
      ("w","§39.4 — Improve, complete specification","—"),
      ("t","§39.4.2 — Improve's ordered field list","—"),
      ("w","§39.4.7 — Improve's use of PhaseState","6.20"),
      ("w","§39.5 — Control, complete specification","—"),
      ("t","§39.5.2 — Control's ordered field list","—")])],
   have=[("b","PhaseState — 23 fields, shared by all five phases"),
         ("b","the five nodes wired and compiled"),
         ("b","13 gate-required Define fields declared"),
         ("b","the planner node, wired, three exits"),
         ("b","artifacts merge, not replace — 6.33"),
         ("b","field_log — dated, with prior value — 6.33"),
         ("p","the field/gate decision — a turn counter, says so in its own comment"),
         ("a","a predicate for “is this field complete”"),
         ("a","field_log.reason — declared, nothing populates it"),
         ("b","the Define metric entry — 01e8f8a")]),

 dict(key="COACH", label="Coaching agent, middleware and tools", sub="containers 4–6 · zone COACH",
   when="the model call itself — what goes in, what comes back, what it may reach for",
   groups=[("4 · Coaching agent", [
      ("t","§26 — Multi-hop retrieval","6.10"),
      ("w","§43.1 — the seven-step computation pattern","—"),
      ("w","§43.2 — show before asking","—"),
      ("t","§43.3 — the A→F session flow","—"),
      ("t","§43.4 — live gate document preview","—"),
      ("w","§43.5 — no external URLs","—"),
      ("w","§43.6 — what the coach must not do","—"),
      ("w","§43.7 — metric literacy: the metric, and the statistic","—")]),
    ("5 · Middleware", [
      ("w","§19.6 — ContradictionDetectionMiddleware, the mid-phase check","7.3 · 7.6")]),
    ("6 · Tools and knowledge", [
      ("w","§23 — the three indexes","9.1"),
      ("w","§29 — the data channel and the universal eight","7.1 · 7.5"),
      ("w","§30 — computation tools and per-phase binding","7.1 · 7.5")])],
   have=[("b","the executor — the only agent in the phase"),
         ("b","8 declared response fields"),
         ("b","the Define SKILL.md — 12 fields, explain · show · ask · confirm"),
         ("b","the metric literacy block in the skill"),
         ("b","mw1 state injection"),("p","mw2 skills — a catalogue, no record it was taken"),
         ("b","mw3 summarising"),("b","mw4 model retry"),("b","mw5 tool retry"),
         ("b","mw6 coaching grader — process, every turn"),
         ("b","mw7 coherence — every turn"),
         ("p","mw8 contradiction — ships inert, import kept"),
         ("b","7 tools bound — 3 retrieval, template, diagram, series, savings"),
         ("b","the evidence index — uploads, chunked, twelve fields"),
         ("b","the capture path checks each value against its declared type — 5dc10ff"),
         ("a","read an artefact"),("a","check_gate_status"),("a","request_human_approval"),
         ("a","the Define phase rubric — six criteria, no text")]),

 dict(key="STORE", label="Persistence", sub="container 8 · zone STORE",
   when="checkpoints during the turn, and the record written after the graph returns",
   groups=[("8 · Persistence and cross-cutting", [
      ("t","§44 — the failure pipeline","8.2"),
      ("t","§46 — the fallback chain and circuit breakers","8.3 · 8.4"),
      ("t","§48 — structured errors","8.1"),
      ("t","§51 — tracing and observability","8.0")])],
   have=[("b","the blob checkpointer — put, get_tuple, list, async wrappers"),
         ("b","the subgraph compiles with none and inherits the parent's"),
         ("b","the case record — fields, change log, citations, uploads"),
         ("p","writes during a node are a no-op"),
         ("p","no connection string = no persistence, and only a log line says so"),
         ("a","resume from a checkpoint — no rollback, no time travel"),
         ("a","a version on the write — last writer wins by default"),
         ("a","the knowledge index — schema exists, nothing ingested"),
         ("a","the case index — prior cases"),
         ("u","whether a checkpoint has ever been written")]),

 dict(key="GATE", label="Validation, gates, escalation", sub="container 7 · zone GATE",
   when="the phase closes: the checks run, the Belt approves, the record is written",
   groups=[("7 · Validation, gates, escalation", [
      ("t","§33 — the nine-step HITL gate","7.3"),
      ("w","§34 — the four-layer validation stack","7.2"),
      ("t","§35 — two tiers of field, and the warning verdict","7.4"),
      ("w","§36 — two graders, and why they are not redundant","7.1"),
      ("t","§37 — mid-phase contradiction and the re-approval cascade","7.6 · 7.3"),
      ("t","§38 — escalation","7.5"),
      ("t","§39.1.11 — conditions: routing and the gate","7.3"),
      ("t","§52 — evaluation and regression testing","7.0"),
      ("w","§63.6 — S-C32, the three cross-phase reference dicts","—"),
      ("w","§63.9 — S-C39, phase_metrics, the per-phase placeholder","—")])],
   have=[("b","2a coherence — middleware, every turn"),
         ("b","assemble() — assembles a real case, 18 keys"),
         ("p","2b field presence — built, runs only at the gate"),
         ("p","gate_review — logs and passes through, never pauses"),
         ("p","gate_apply — applies nothing, by design; the route does the write"),
         ("a","2c constraints"),("a","2d the phase rubric — the gate's own grader"),
         ("a","the five phase rubrics have coverage lists and no text"),
         ("a","the Store copy Measure reads — written by the mapper that does not fire")]),

 dict(key="OPS", label="Cross-cutting — reliability and governance", sub="zone OPS",
   when="not on the turn path: tracing, errors, the register, the guards, deleting v1",
   groups=[], clean="its markers are carried by container 8, above",
   have=[("b","the drift-check hook on every commit"),
         ("b","verify_built.py — 32 checks, zero disagreements at 62d7f17"),
         ("b","the step register and the gap register"),
         ("a","a check that compares the tree against the framework's own documentation")]),
]

# ------------------------------------------------- what the frameworks say
# VERIFIED by me at docs.langchain.com and learn.microsoft.com, 23 Sep 2026.
FRAMEWORK = [
 ("“the runtime restarts the entire node from the beginning — it does not resume from the "
  "exact line where interrupt() was called”",
  "so the gate-document write must be safe to perform twice",
  "6.42", "docs.langchain.com/oss/python/langgraph/interrupts"),
 ("“Do not perform non-idempotent operations before interrupt()… Do not create new records "
  "without checking if they exist.”",
  "a documented rule pointed straight at the gate write",
  "6.42", "docs.langchain.com/oss/python/langgraph/interrupts"),
 ("interrupt() is documented in node functions and in tools. Middleware is not mentioned.",
  "the stop belongs in a node — 7.3's clause 1 is superseded in placement, not in substance",
  "6.44", "docs.langchain.com/oss/python/langgraph/interrupts"),
 ("“To use interrupt(), you need: 1. A checkpointer to persist the graph state”",
  "and whether ours has ever written is not knowable from the tree — assert it at runtime",
  "7.3", "docs.langchain.com/oss/python/langgraph/interrupts"),
 ("“it is assumed that all updates to that key should override it” — with no reducer declared",
  "every accumulating channel needs a reducer, or a write site can silently replace",
  "S26", "docs.langchain.com/oss/python/langgraph/graph-api"),
 ("separate input_schema and output_schema are supported on StateGraph",
  "the boundary the output mapper is meant to own is a first-class framework feature",
  "S25", "docs.langchain.com/oss/python/langgraph/graph-api"),
 ("“if you don't explicitly specify a strategy, then by default the last writer wins”",
  "the case-record write carries no version, and a second writer arrives at stage 7",
  "S25", "learn.microsoft.com · Azure Blob concurrency"),
]

# ------------------------------------------------- real, and not carded
FINDINGS = [
 ("baseline_estimate is stored as a sentence fragment",
  "the live 200 at 01e8f8a carries baseline_estimate \u201c\u2026averaging 12.78.\u201d beside target_value \u201c3%\u201d. "
  "\u00a763.1 B7 requires both as DISCRETE values because Control parses them for target-versus-actual. "
  "The type is str, so the type check cannot catch it; only a value check can. Blocks nothing in flight.",
  "RELAYED \u00b7 01e8f8a \u00b7 findings list"),
 ("CO-1 — captured values do not carry their declared type",
  "four gate-required Define fields are declared structured and captured as prose, so no gate "
  "document can assemble on real data. ADMITTED: it blocks 6.20's live clause and 6.42 entirely. "
  "Needs a number.", "RELAYED · 62d7f17"),
 ("6.48 — the graph owns its boundary, with a version on the write",
  "the output mapper is not called and the HTTP route writes instead; the write carries no version "
  "while Azure defaults to last-writer-wins.", "proposed · not in the register"),
 ("6.49 — accumulating channels carry reducers",
  "merging is done by hand in application code where the framework offers a reducer that cannot "
  "be forgotten.", "proposed · not in the register"),
 ("§16's persistence claim contradicts the tree",
  "the G-44 rule says the wrapper's inner invoke persists PhaseState across Belt turns; the route "
  "comment, the turn-two test and 6.33's whole design all say it does not.",
  "RELAYED · 62d7f17 · first output of the conformance pass"),
 ("§43.1–§43.7 — seven coaching-behaviour markers owned by nothing",
  "the seven-step computation pattern, show before asking, the A→F session flow, the live gate "
  "preview, no external URLs, what the coach must not do, metric literacy. The largest unowned "
  "block in the architecture, and it sits inside the vertical being refactored.", "DERIVED"),
 ("§63.9 — phase_metrics reads owned by nothing while 6.20 builds it",
  "6.20 should claim the marker in its commit, or it will read open after the work has landed.",
  "DERIVED"),
 ("Project members and sign-in",
  "a case is opened against a free-text name. Out of scope now. The constraint on work in flight: "
  "field_log entries and the gate approval record each carry an ACTOR value from the outset, so "
  "identity can be substituted later without changing either structure.",
  "founder, 23 Sep · forward dependency"),
]

# NEXT is no longer declared here. It is DERIVED by stories.next_story(): the
# top-ranked story that is not done, whose status comes from Appendix H.


# ---------------------------------------------- the architecture, folded in
# Which arch_view blocks belong under which column. The content itself lives in
# arch_view.py (RELAYED from the tree audit at 208e4a7 + the ratified sections).
SPEC = {
 "SUP":   dict(level="LEVEL1"),
 "PHASE": dict(level="LEVEL2", nodes=["Phase planner"], phases=True),
 "COACH": dict(nodes=["Phase executor \u2014 the coach"], middleware=True, tools=True),
 "GATE":  dict(nodes=["Validation stack", "Gate review", "Gate apply"], validation=True),
 "STORE": dict(stores=True),
}


# --------------------------------------------------- the procedure's stages
# Membership and counts are DERIVED at build time from the step numbers.
# Only stage 8's name is quoted from the document ("Part 7 — Stage 8: Reliability",
# carried verbatim by the repo board). The others are described from the titles of
# the steps they contain and are marked as such.
STAGE_NOTE = ("A stage is the step-number prefix: 6.42 is in stage 6. Membership and the counts below "
              "are derived from the register. Only stage 8 carries a name the document states; the rest "
              "are described from the steps they contain.")
STAGES = {
 "2": ("Upgrade the foundation", "dependencies, async, the LLM factory", False),
 "3": ("State, storage and the boundary", "SupervisorState, PhaseState, the mappers, the schemas", False),
 "4": ("The graphs", "the Define subgraph, the supervisor, the remaining four", False),
 "5": ("Retrieval and tools", "the three lookups, twenty computation tools, per-phase binding", False),
 "6": ("The coaching loop", "planner, executor, middleware, the write paths, the governance guards", False),
 "7": ("Validation, gates and escalation", "the four layers, the HITL gate, the approve endpoint", False),
 "8": ("Reliability", "telemetry, structured errors, timeouts, circuit breakers", True),
 "9": ("Indexes", "the knowledge corpus, the case index, the deployment quota", False),
 "10": ("The browser", "rendering the turn, progress, the gate screen, errors, streaming", False),
 "11": ("Close-out", "delete v1, close the governance register", False),
}
